import { DIMENSION_LABELS, type FitReport, AD_ANGLE_LABELS } from "@/types/domain";

export function toMarkdown(args: { report: FitReport; url: string; title: string; createdAt: Date }): string {
  const { report } = args;
  const lines: string[] = [];

  lines.push(`# ${args.title}`, "");
  lines.push(`**Landing page:** ${args.url}`);
  lines.push(`**Analysed:** ${args.createdAt.toISOString().slice(0, 10)}`);
  lines.push(`**Overall fit:** ${report.overallScore}/100 (grade ${report.grade})`);
  lines.push(`**Confidence:** ${Math.round(report.confidence * 100)}%`, "");
  lines.push(`> ${report.verdict}`, "");
  lines.push(report.summary, "");

  if (report.criticalIssues.length > 0) {
    lines.push("## Fix these first", "");
    for (const issue of report.criticalIssues) {
      lines.push(`### ${issue.title}`, "");
      lines.push(`**Severity:** ${issue.severity}`, "");
      lines.push(issue.detail, "");
      if (issue.evidence?.adQuote) lines.push(`- Ad says: "${issue.evidence.adQuote}"`);
      if (issue.evidence?.pageQuote) lines.push(`- Page says: "${issue.evidence.pageQuote}"`);
      if (issue.evidence?.selector) lines.push(`- Found at: \`${issue.evidence.selector}\``);
      lines.push("");
    }
  }

  if (report.quickWins.length > 0) {
    lines.push("## Quick wins", "");
    lines.push("| Change | Effort | Impact |", "| --- | --- | --- |");
    for (const win of report.quickWins) {
      lines.push(`| ${win.title} | ${win.effort.toLowerCase()} | ${win.impact}/10 |`);
    }
    lines.push("");
  }

  lines.push("## Scores", "");
  lines.push("| Dimension | Score | Weight |", "| --- | --: | --: |");
  for (const dimension of report.dimensions) {
    const score = dimension.applicable ? `${dimension.score}` : "n/a";
    const weight = dimension.applicable ? `${Math.round(dimension.weight * 100)}%` : "—";
    lines.push(`| ${DIMENSION_LABELS[dimension.dimension]} | ${score} | ${weight} |`);
  }
  lines.push("");

  if (report.strengths.length > 0) {
    lines.push("## What is working", "");
    report.strengths.forEach((s) => lines.push(`- ${s}`));
    lines.push("");
  }
  if (report.weaknesses.length > 0) {
    lines.push("## What is not", "");
    report.weaknesses.forEach((w) => lines.push(`- ${w}`));
    lines.push("");
  }

  lines.push("## Detailed findings", "");
  for (const dimension of report.dimensions) {
    if (!dimension.applicable) continue;
    lines.push(`### ${DIMENSION_LABELS[dimension.dimension]} — ${dimension.score}/100`, "");
    lines.push(dimension.summary, "");

    if (dimension.problems.length > 0) {
      lines.push("**Problems**", "");
      for (const problem of dimension.problems) {
        lines.push(`- **${problem.title}** (${problem.severity.toLowerCase()}) — ${problem.detail}`);
      }
      lines.push("");
    }
    if (dimension.recommendations.length > 0) {
      lines.push("**Recommendations**", "");
      for (const rec of dimension.recommendations) {
        lines.push(`- **${rec.title}** (${rec.priority.toLowerCase()} priority, ${rec.effort.toLowerCase()} effort) — ${rec.detail}`);
        if (rec.example) lines.push(`  > ${rec.example}`);
      }
      lines.push("");
    }
  }

  const rewrites = Object.entries(report.rewrites).filter(([, v]) => Array.isArray(v) && v.length > 0);
  if (rewrites.length > 0) {
    lines.push("## Suggested rewrites", "");
    for (const [slot, options] of rewrites) {
      lines.push(`**${slot}**`, "");
      (options as string[]).forEach((o) => lines.push(`- ${o}`));
      lines.push("");
    }
  }

  if (report.clusters.length > 1) {
    lines.push("## Ad angles and page blueprints", "");
    for (const cluster of report.clusters) {
      lines.push(`### ${cluster.label} (${AD_ANGLE_LABELS[cluster.angle]})`, "");
      lines.push(cluster.rationale, "");
      lines.push(`- **Hero:** ${cluster.blueprint.hero}`);
      lines.push(`- **Headline:** ${cluster.blueprint.headline}`);
      lines.push(`- **Subheadline:** ${cluster.blueprint.subheadline}`);
      lines.push(`- **CTA:** ${cluster.blueprint.cta}`);
      if (cluster.blueprint.benefits.length > 0) {
        lines.push("- **Benefits:**");
        cluster.blueprint.benefits.forEach((b) => lines.push(`  - ${b}`));
      }
      if (cluster.blueprint.faq.length > 0) {
        lines.push("- **FAQ:**");
        cluster.blueprint.faq.forEach((f) => lines.push(`  - **${f.question}** ${f.answer}`));
      }
      lines.push("");
    }
  }

  lines.push("---", "", `Generated by Ad-to-Landing Page Fit Analyzer.`);
  return lines.join("\n");
}
